

#define MODE_NORMAL_LINE_FOLLOWING 0
#define MODE_NORMAL_OBSTACLE_FOLLOWING 1
#define MODE_NORMAL_OBSTACLE_AVOIDANCE 2
#define MODE_PARALLEL_LINE_FOLLOWING 3
#define MODE_PARALLEL_OBSTACLE_FOLLOWING 4
#define MODE_PARALLEL_OBSTACLE_AVOIDANCE 5
#define MODE_REMOTE_CONTROL 6

