#ifndef __ARDUINO_CAR_H__
#define __ARDUINO_CAR_H__

#define MODE_NONE                        0
#define MODE_NORMAL_LINE_FOLLOWING       1
#define MODE_NORMAL_OBSTACLE_FOLLOWING   2
#define MODE_NORMAL_OBSTACLE_AVOIDANCE   3
#define MODE_PARALLEL_LINE_FOLLOWING     4
#define MODE_PARALLEL_OBSTACLE_FOLLOWING 5
#define MODE_PARALLEL_OBSTACLE_AVOIDANCE 6
#define MODE_REMOTE_CONTROL              7
#define MODE_APP_CONTROL                 8
#define MODE_COMPASS_CALIBRATION         9

#endif // __ARDUINO_CAR_H__